[build]
  publish = "dist"
  command = "npm run generate"
  functions = "api"
 
[build.environment]
  NODE_VERSION = "14"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"